### ISSUE TITLE
flickr.people.getPhotos not unmarshalling list of Photos into slice

### ISSUE THREAD

**Issue by focusaurus** [masci/flickr#17]
From what I can tell there's a missing slice in the go struct used to unmarshall ListPhotosResponse. I would expect `PhotoList.Photo` to have type `[]Photo` but it's just a single Photo struct. I can't get at the individual photo tags that are present in the XML response.

**Comment by masci** [comment]
Hey @focusaurus unfortunately I can't look into this, but if you're willing to open a PR with a fix I'll be happy to merge!

**Comment by focusaurus** [comment]
OK I was able to adjust the xml unmarshall struct field tags and change the struct shape. With some test parsing code it seems to now be doing what I expect so I should be able to send a PR.

**Comment by focusaurus** [comment]
Will open a PR shortly but it's not a backward compatible change so maybe you'll need to bump to v3?
