### ISSUE TITLE
status code : 411

### ISSUE THREAD

**Issue by denisov** [masci/flickr#3]
Hi

UploadFile doesn't work for me. 
`resp, err := flickr.UploadFile(client, "/home/andrey/cat.jpg", nil)`

It return the html page with error

```
<!-- status code : 411 -->
<!-- No Content Length : POST -->
<!-- host machine: r13.ycpi.dea.yahoo.net -->
<!-- timestamp: 1463678271.000 -->
<!-- url: https://up.flickr.com/services/upload/-->
```

`http_client` sets `Transfer-Encoding: chunked` header but doesn't set `Content-Lenght` header. I guess that's the reason.

I am on Xubuntu 16.04

```
$ go version
go version go1.6.2 linux/amd64
```

There is another flickr library https://github.com/mncaudill/go-flickr/ It calculate length manualy https://github.com/mncaudill/go-flickr/blob/master/flickr.go#L164

**Comment by masci** [comment]
Thanks for the feedback @denisov I'll check this out asap

**Comment by masci** [comment]
Still investigating but related to this: https://github.com/golang/go/issues/14391
Works with go < 1.6.2 or v.1.6.2 with `GODEBUG=http2client=0` env var set.

**Comment by denisov** [comment]
Thanks for letting me know

**Comment by masci** [comment]
I don't like the fix for this bug but I wasn't able to understand why Flickr fails when we use the h2 client along with a chunked POST request. 
Added a comment to remind for a further investigation.
